import 'package:zomato_clone/utils/globle_model.dart';
import 'package:zomato_clone/utils/globle_product_list.dart';
int selectIndexDisplay=0;
List indexType=List.filled(typeListFill.length, typeListFill.length+10,growable: true);
bool valueBool=true;
FoodModel? exploreList;
FoodModel? productListModelUse;
FoodModel? productListModelUseJoin;
List emtyeProductList=[];
bool boolColorTabBar=true;
bool fastFindBool=false;
bool tabCreateBool=false;